### ISSUE TITLE
For Dr Dreck

### ISSUE THREAD

**Issue by Stoppedwumm** [Stoppedwumm/StoppedwummDownloader#5]
Hello Dr Dreck,
please respond to this issue to show that your active.
Thank you @DrDreck

**Comment by DrDreck** [comment]
I don't think I will be releasing this project. I don't have very much time at the moment. Sorry!

**Comment by StoppedwummSites** [comment]
> I don't think I will be releasing this project. I don't have very much time at the moment. Sorry!

Sorry, but I renamed a bit, License is the same and you have credits in the readme.
